contact:
  first_name: "Ann"
  last_name:  "Heslin"
  email:      "annheslinslade@gmail.com"
  phone:      "650-766-5648"
  zip_code:   "10016"

submission:
  borough:               "Manhattan"
  topic:                 "Bicycle Lanes and Programs"
  place_type:            "Street or Sidewalk"
  description_template: |
        Hi DOT. Thank you for all the work that you do to help keep our bikers safe.
    
  why_writing:           "Concern"